# NetlfiyCMS configuration
# https://www.netlifycms.org/docs/configuration-options/#configuration-file
backend:
  name: git-gateway

media_folder: public/img
public_folder: /img

collections:
  - name: 'aktuelles'
    label: 'Aktuelles'
    folder: 'content/_aktuelles'
    format: 'frontmatter'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    editor:
      preview: false
    fields:
      - { label: 'Titel', name: 'title', widget: 'string' }
      - { label: 'Text', name: 'text', widget: 'markdown' }
