# NetlfiyCMS configuration
# https://www.netlifycms.org/docs/configuration-options/#configuration-file
backend:
  name: git-gateway

media_folder: public/img
public_folder: /img

collections:
  - name: 'aktuelles'
    label: 'Post'
    folder: 'content/_aktuelles'
    format: 'frontmatter'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    editor:
      preview: false
    fields:
      - { label: 'Titel', name: 'title', widget: 'string' }
      - label: 'Datum'
        name: 'date'
        widget: 'datetime'
        date_format: 'DD.MM.YYYY'
        time_format: false
      - { label: 'Text', name: 'body', widget: 'markdown' }
  - name: 'rubriken'
    label: 'Rubrik'
    folder: 'content'
    format: 'frontmatter'
    create: false
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    editor:
      preview: false
    fields:
      - { label: 'Titel', name: 'title', widget: 'string' }
      - { label: 'Banner', name: 'bannerImage', widget: 'image', required: false }
      - { label: 'Inhalt', name: 'body', widget: 'markdown' }
